fineduc/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
import myapp.views as myapp

urlpatterns = [
    path('', myapp.redirect_index),
    path('getCities/', myapp.getCities, name="get"),
    path('admin/', admin.site.urls),
    path('index/', myapp.index, name="index"),
    path('register/', myapp.register, name="register"),
    path('login/', myapp.login, name="login"),
    path('logout/', myapp.logout, name="logout"),
    path('request/', myapp.request, name="request"),
    path('profile/', myapp.profile, name="profile"),
    path('seeProfile/', myapp.seeProfile, name="seeProfile"),
]

if settings.DEBUG:  
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)  

myapp/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Profile(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=40)
    cellphone = models.CharField(max_length=11)
    state = models.CharField(max_length=2, blank=True)
    city = models.CharField(max_length=20, blank=True)


    image = models.ImageField(upload_to="profile-images", blank=True)

    
    bio = models.TextField(blank=True)
    link_youtube = models.CharField(max_length=150, blank=True)
    link_instagram = models.CharField(max_length=150, blank=True)
    link_facebook = models.CharField(max_length=150, blank=True)
    link_linkedin = models.CharField(max_length=150, blank=True)

    def __str__(self) -> str:
        return self.name


class Request(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    description = models.TextField(max_length=250)
    amount = models.FloatField()

    def __str__(self) -> str:
        return f"{self.user.username}_req"

myapp/forms.py
from django import forms

from pyUFbr.baseuf import ufbr

class RegisterForm(forms.Form):
    stateOptions = []
    for uf in ufbr.list_uf:
        stateOptions.append([uf, uf])
    cityOptions = []
    for cityy in ufbr.list_cidades("AC"):
        cityOptions.append([cityy, cityy])
    
    name = forms.CharField(label="Nome", max_length=40, required=True)
    username = forms.CharField(max_length=40, required=True)
    email = forms.EmailField(label="Email", required=True, error_messages={"invalid": "Digite um email válido"})
    cellphone = forms.CharField(widget=forms.NumberInput(), label="Telefone", max_length=11, required=True)
    state = forms.ChoiceField(label="Estado", choices=stateOptions)
    city = forms.ChoiceField(label="Cidade", choices=cityOptions)
    password = forms.CharField(label="Senha", widget=forms.PasswordInput(), min_length=8)

class RequestForm(forms.Form):
    description = forms.CharField(label="Descrição", widget=forms.Textarea)
    amount = forms.FloatField(label="Quantidade", required=True)

class LoginForm(forms.Form):
    username = forms.CharField(label="Username", required=True)
    password = forms.CharField(label="Senha",widget=forms.PasswordInput(), required=True)

myapp/views.py
from django.shortcuts import render, redirect

from pyUFbr.baseuf import ufbr

from .models import Profile, Request
from django.http.request import HttpRequest
from django.http import JsonResponse
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, logout as logoutt, login as loginn

from .forms import RegisterForm, RequestForm, LoginForm

from django.core.files.storage import FileSystemStorage

# Create your views here.

def redirect_index(request: HttpRequest):
    return redirect("index")

def index(request: HttpRequest):
    requests = Request.objects.all()

    data = []

    for req in requests:
        profile = Profile.objects.get(user_id=req.user.pk)
        checkImageExists(profile)
        data.append({"profile":profile,"request": req})

    return render(request, "myapp/index.html", context={"data": data})

def register(request: HttpRequest):
    form = RegisterForm()
    if request.POST:
        try:
            User.objects.get(username=request.POST.get("username"))
            form = RegisterForm(request.POST)
            form.add_error("username", "Este username já está em uso")
            return render(request, "myapp/register.html", context={"states": ufbr.list_uf, "form": form})
        except User.DoesNotExist:
            form = RegisterForm(request.POST)
            if form.is_valid:
                user = User.objects.create_user(
                    request.POST.get("username"),
                    request.POST.get("email"),
                    request.POST.get("password")
                )

                Profile.objects.create(
                    user_id = user.pk,
                    name = request.POST.get("name"),
                    cellphone = request.POST.get("cellphone"),
                    state = request.POST.get("state"),
                    city = request.POST.get("city"),
                )

                loginn(request, user)
                return redirect("index")
            else:
                print("form errado")
    return render(request, "myapp/register.html", context={"states": ufbr.list_uf, "form": form })

def login(request: HttpRequest):
    form = LoginForm()
    if request.POST:
        user = authenticate(
            username=request.POST.get("username"),
            password=request.POST.get("password")
        )
        if user is not None:
            loginn(request, user)
            return redirect("index")
        else:
            form = LoginForm(request.POST)
    return render(request, "myapp/login.html", context={"form": form})

def logout(request: HttpRequest):
    logoutt(request)
    return redirect("index")

def request(request: HttpRequest):
    if request.user.is_authenticated:
        rq = None
        try:
            rq = Request.objects.get(user_id=request.user)
            if request.POST:
                rq.description = request.POST.get("description")
                rq.amount = request.POST.get("amount")
                rq.save()
        except Request.DoesNotExist:
            if request.POST:
                rq = Request.objects.create(
                    user_id = request.user.pk,
                    description = request.POST.get("description"),
                    amount = request.POST.get("amount")
                )
        form = RequestForm(initial={
            "description": rq.description,
            "amount": rq.amount
            }) if rq else RequestForm()
        return render(request, "myapp/request.html", context={"form": form})
    else:
        return redirect("login")


def verifyLink(link):
    if link[0:8] != "https://" and link[0:7] != "http://" and link != "":
        link = f"https://{link}"
    return link

def profile(request: HttpRequest):
    if request.user.is_authenticated:
        profile = Profile.objects.filter(user_id=request.user).get()
        checkImageExists(profile)
        if request.POST:
            if request.FILES:
                fss = FileSystemStorage()
                if profile.image:
                    if fss.exists(str(profile.image).split("/")[-1]):
                        fss.delete(str(profile.image).split("/")[-1])
                file = fss.save(request.user.pk, request.FILES.get("image"))
                profile.image = fss.url(file)
            
            profile.name = request.POST.get("name")
            profile.bio = request.POST.get("bio")
            profile.link_facebook = verifyLink(request.POST.get("link_facebook"))
            profile.link_instagram = verifyLink(request.POST.get("link_instagram"))
            profile.link_linkedin = verifyLink(request.POST.get("link_linkedin"))
            profile.link_youtube = verifyLink(request.POST.get("link_youtube"))
            profile.cellphone = request.POST.get("cellphone")
            profile.state = request.POST.get("state")
            profile.city = request.POST.get("city")
            profile.save()
        return render(request, "myapp/profile.html", context={"states": ufbr.list_uf, "cities": ufbr.list_cidades(profile.state), "profile": profile})
    else:
        return redirect("register")


def seeProfile(request):
    if request.GET:
        try:
            profile = Profile.objects.get(user_id=request.GET.get("user_id"))
            checkImageExists(profile)
            req = Request.objects.get(user_id=request.GET.get("user_id"))
            return render(request, "myapp/see_profile.html", context={"profile": profile, "request": req})
        except Profile.DoesNotExist:
            pass
    return redirect("index")


def checkImageExists(profile):
    print(profile.image)
    if not profile.image:
        return False
    fss = FileSystemStorage()
    if not fss.exists(str(profile.image).split("/")[-1]):
        profile.image = None
        profile.save()
        return False
    return True


def getCities(request):
    data = {"cities": ufbr.list_cidades(request.POST.get("state"))}
    return JsonResponse(data)

myapp/templates/myapp/base.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <title>Fineduc</title>
</head>
<body>
    <header>
        <div class="left-header-half">
            <nav class="image-content">
                <a href="{% url 'index' %}">
                    <div class="image"></div>
                </a>
            </nav>
        </div>
        <!-- <div class="middle-header-half">
            <nav>
                <input type="text" name="search" id="search" placeholder="Digite o ID ou título">
            </nav>
        </div> -->
        <div class="right-header-half">
            <div class="login-area">
                {% if user.is_authenticated %}
                    <a href="{% url 'profile' %}" class="profile">
                        <div style="width: 55px;height: 55px;border-radius: 27.5px;background-color: black;"></div>
                    </a>
                    <nav>
                        <a class="login-buttom" href="{% url 'logout' %}">Sair</a>
                    </nav>
                {% else %}
                    <nav>
                        <a class="login-buttom" href="{% url 'register' %}">Cadastre-se</a>
                    </nav>
                    <nav>
                        <a class="login-buttom" href="{% url 'login' %}">Login</a>
                    </nav>
                {% endif %}
                <nav>
                    <a class="login-buttom-filled" href="{% url 'request' %}">
                        {% if user.is_authenticated %}
                            Ver meu pedido
                        {% else %}
                            Fazer um pedido
                        {% endif %}
                    </a>
                </nav>
            </div>
        </div>
    </header>

    <div class="main">
        {% block content %} {% endblock %}
    </div>

    <footer></footer>

    <script>
        var csrftoken = '{{ csrf_token }}';
    </script>
    <script src="{% static 'js/city_selector.js' %}"></script>
</body>
</html>

myapp/templates/myapp/index.html
{% extends 'myapp/base.html' %}

{% load static %}

{% block content %}

<link rel="stylesheet" href="{% static 'css/index.css' %}">
    
<!-- <div class="index-header">
    <h1 class="index-header-title">Conheça alguns pedidos</h1>
    <form class="filter">
        <label for=""><h2 class="filter-title">Filtrar por: </h2></label>
        <select name="filter" id="">
            <option value="">Última hora</option>
            <option value="">Último dia</option>
            <option value="">Últimos 3 dias</option>
            <option value="" selected>Útimos 7 dias</option>
        </select>
    </form>
</div> -->

<h1>Pedidos feitos</h1>

<div class="cards">

    {% for card in data %}

        <form action="{% url 'seeProfile' %}" method="get" id="{{card.profile.user_id}}">
            <input type="hidden" name="user_id" value="{{card.profile.user_id}}">
        </form>

        
        <a onclick="document.getElementById('{{card.profile.user_id}}').submit()" class="card">
            <div class="card-header">
                <img
                    {% if card.profile.image %}
                        src="{{card.profile.image}}"
                    {% else %}
                        src="{% static 'images/user.png' %}"
                    {% endif %}
                alt="">
                <h4 class="card-title">{{card.profile.name}}</h4>
            </div>
            <div class="card-content">
                <p class="card-desc">{{card.request.description}}</p>
            </div>
            <div class="card-goal">
                Meta de {{card.request.amount}} reais
            </div>
        </a>

    {% endfor %}

</div>

{% endblock %}

myapp/templates/myapp/login.html
{% extends 'myapp/base.html' %}

{% load static %}

{% block content %}

    <link rel="stylesheet" href="{% static 'css/account.css' %}">

    <div class="account-header">
        <h1 class="account-header-title">Login</h1>
        <p>Não possui uma conta? <a href="{% url 'register' %}">Cadastre-se</a></p>
    </div>

    <div class="account-body">
        <form class="account-form" action="{% url 'login' %}" method="POST">
            {% csrf_token %}
            {{form}}
            <button type="submit">Entrar</button>
        </form>
    </div>

{% endblock %}

myapp/templates/myapp/profile.html
{% extends 'myapp/base.html' %}

{% load static %}

{% block content %}

    <link rel="stylesheet" href="{% static 'css/profile.css' %}">    
    <div class="profile-header">
        <h1 class="profile-header-title">Meus dados</h1>
    </div>

    <div class="profile-body">
        <form class="profile-form" enctype="multipart/form-data" action="{% url 'profile' %}" method="POST">
            {% csrf_token %}
            <div class="my-profile">
                <div class="profile-identity">
                    <label for="imageInput">
                        <img class="profile-img"
                        {% if profile.image %}
                            src="{{profile.image}}"
                        {% else %}
                            src="{% static 'images/user.png' %}"
                        {% endif %}
                        alt="">
                        <img id="cam" src="{% static 'images/camera.png' %}" alt="">
                        <input type="file" name="image" accept="image/" id="imageInput">
                    </label>
                    {{user.username}}
                </div>
                <div class="name-and-bio">
                    <label for="">Nome</label>
                    <input type="text" name="name" value="{{profile.name}}">
                    <label for="">Bio</label>
                    <textarea type="text" name="bio">{{profile.bio}}</textarea>
                </div>
            </div>
            <div class="social-medias">
                <label for="">Redes Sociais</label>
                <div class="social-medias-content">
                    <input type="text" name="link_instagram" value="{{profile.link_instagram}}" placeholder="Link do Instagram">
                    <input type="text" name="link_facebook" value="{{profile.link_facebook}}" placeholder="Link do Facebook">
                    <input type="text" name="link_youtube" value="{{profile.link_youtube}}" placeholder="Link do Youtube">
                    <input type="text" name="link_linkedin" value="{{profile.link_linkedin}}" placeholder="Link do Linkedin">
                </div>
            </div>
            <div class="cellphone">
                <label for="">Telefone</label>
                <input type="text" name="cellphone" value="{{profile.cellphone}}" placeholder="Número de Telefone">
            </div>
            <div class="place">
                <label>Localização</label>
                <div class="place-row">
                    <label>Estado:</label>
                    <select name="state" id="id_state">
                        {% for state in states %}
                            <option {% if state == profile.state %} selected {% endif %} value="{{state}}">{{state}}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="place-row">
                    <label>Cidade:</label>
                    <select name="city" id="id_city">
                        {% for city in cities %}
                            <option {% if city == profile.city %} selected {% endif %} value="{{city}}">{{city}}</option>
                        {% endfor %}
                    </select>
                </div>
            </div>
            <button type="submit">Atualizar dados</button>
        </form>
    </div>

{% endblock %}

myapp/templates/myapp/register.html
{% extends 'myapp/base.html' %}

{% load static %}

{% block content %}

    <link rel="stylesheet" href="{% static 'css/account.css' %}">

    <div class="account-header">
        <h1 class="account-header-title">Faça seu cadastro</h1>
        <p>* Todos os dados são obrigatórios</p>
    </div>

    <div class="account-body">
        <form class="account-form" action="{% url 'register' %}" method="POST">
            {% csrf_token %}
            {{ form }}
            <button type="submit">Cadastrar-se</button>
        </form>
    </div>

    {{form.errors}}

{% endblock %}

myapp/templates/myapp/request.html
{% extends 'myapp/base.html' %}

{% load static %}

{% block content %}

    <link rel="stylesheet" href="{% static 'css/account.css' %}">

    <div class="account-header">
        <h1 class="account-header-title">Pedido</h1>
    </div>

    <div class="account-body">
        <form class="account-form" action="{% url 'request' %}" method="POST">
            {% csrf_token %}
            {{form}}
            <button type="submit">Finalizar</button>
        </form>
    </div>

{% endblock %}

myapp/templates/myapp/see_profile.html
{% extends 'myapp/base.html' %}

{% load static %}

{% block content %}

    <link rel="stylesheet" href="{% static 'css/see_profile.css' %}">
    
    <div class="profile-content">
        <div class="profile-header">
            <div class="profile-identity">
                <div class="image-and-medias">
                    <div class="social-medias-icons">
                        {% if profile.link_facebook %}
                        <a href="{{profile.link_facebook}}">
                            <img src="{% static 'images/facebook.png' %}" alt="Facebook">
                        </a>
                        {% endif %}
                        {% if profile.link_instagram %}
                        <a href="{{profile.link_instagram}}">
                            <img src="{% static 'images/instagram.png' %}" alt="Instagram">
                        </a>
                        {% endif %}
                    </div>
                    <img class="profile-img"
                        {% if profile.image %}
                            src="{{profile.image}}"
                        {% else %}
                            src="{% static 'images/user.png' %}"
                        {% endif %}
                    alt="">
                    <div class="social-medias-icons">
                        {% if profile.link_youtube %}
                        <a href="{{profile.link_youtube}}">
                            <img src="{% static 'images/youtube.png' %}" alt="YoutTube">
                        </a>
                        {% endif %}
                        {% if profile.link_linkedin %}
                        <a href="{{profile.link_linkedin}}">
                            <img src="{% static 'images/linkedin.png' %}" alt="Linkedin">
                        </a>
                        {% endif %}
                    </div>
                </div>
                <h2>{{profile.name}}</h2>
                {{profile.city}} - {{profile.state}}
                <h1>Bio</h1>
                <p>{{profile.bio}}</p>
                <h1>Telefone</h1>
                <p>{{profile.cellphone}}</p>
            </div>
        </div>
        {% if request %}
            <div class="request-content">
                <h1>Pedido</h1>
                <p>{{request.description}}</p>
                <h2>Meta</h2>
                <p>{{request.amount}} reais</p>
            </div>
        {% endif %}
    </div>

{% endblock %}